Add desktop version
Dadadon/Microverse-portfolio pull request #4
Opened 2022-07-07 18:33 UTC by Dadadon

- Used media queries in my CSS file to make my desktop version look like the template I selected
- used Grid and Flexbox to lay out the elements on the page

2022-07-07 20:50 UTC, vechicin requested changes
# Hi @Dadadon ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 20:50 UTC, vechicin commented on style.css
>  @media all and (max-width: 500px) {
According to the principles of mobile-first development, you don't need media queries for your mobile design. Please remove this media query.

2022-07-07 20:50 UTC, vechicin commented on desktop.css
> +@media all and (min-width: 501px) {
I recommend you keep all of your styling in one file and fix your media query.

<img width="891" alt="Screen Shot 2022-07-07 at 15 29 51" src="https://user-images.githubusercontent.com/82426682/177865931-6e234651-785b-4e07-9a3b-abe758986918.png">

2022-07-07 20:50 UTC, vechicin commented on desktop.css
> +  }
Your project cards don't quite look like those from the Figma design. Take a closer look at the template design and fix the margins/paddings.

<img width="1047" alt="Screen Shot 2022-07-07 at 15 32 45" src="https://user-images.githubusercontent.com/82426682/177866314-d876e364-aba9-4535-8d15-ad3c7dc759dd.png">

2022-07-07 20:50 UTC, vechicin commented on desktop.css
> +  }
This section is missing the `border-radius` in the background's upper right corner.

The margins/paddings for this content's section don't match that of the template design. Please review it and fix it.

You're missing the grey dividers between each technology category (Languages, Frameworks, Skills)

2022-07-07 20:50 UTC, vechicin commented on desktop.css
> +  }
The form's input fields style doesn't match those of the template design. Please review the Figma template and fix them.

2022-07-07 20:50 UTC, vechicin commented on desktop.css
> +    font-weight: 500;
None of your `font-weight` rules are working. That is likely because you didn't import different font weights from Fonts. Please refer to [this video](https://www.youtube.com/watch?v=mRoBBOTYNz4&t=184s) and fix them.

2022-07-08 16:08 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] As the previous code reviewer asked, you must import the font family with the font weights you use in the project in order for it to work correctly.
- [ ] Kindly place all your CSS in one file and use `@media` queries as a breakpoint for your Desktop styling as the previous code reviewer mentioned.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 16:40 UTC, Dadadon commented on desktop.css
> +@media all and (min-width: 501px) {
Isn't refactoring a good coding practice?

2022-07-08 16:55 UTC, Ugboaja-Uchechi approved these changes
Hi @Dadadon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- Good job with your design 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 17:02 UTC, merged